---
version: '2'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql_java
    command: --default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql
    volumes:
      - ./testData/sql/init.sql:/data/application/init.sql
    environment:
      MYSQL_DATABASE: userdb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
